name: CI/CD for Next.js

# Trigger the workflow on push or pull request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs to run
jobs:
  build:
    runs-on: ubuntu-latest

    # Define the steps for the build job
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js for the frontend
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Install dependencies and build the Next.js frontend
      - name: Install dependencies
        run: |
          npm install

      # Build the Next.js frontend
      - name: Build Next.js
        run: |
          npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Deploy job runs only after build job succeeds

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Deploy the frontend using Vercel CLI
      - name: Deploy to Vercel
        run: |
          npm install -g vercel
          vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
